### ISSUE TITLE
typo RunnableLamda in chaper05

### ISSUE THREAD

**Issue by arrowkato** [GenerativeAgents/agent-book#21]
https://github.com/GenerativeAgents/agent-book/blob/351f98fb5f8a0c137f618fbd17143731433d2ffb/chapter05/notebook.ipynb#L335

誤
chain デコレーターを使った RunnableLamda の実装

正
chain デコレーターを使った RunnableLambda の実装 

多分 typo だと思います。

**Comment by os1ma** [comment]
こちら修正しました。ご指摘ありがとうございます！
