### ISSUE TITLE
第６章 6.5. 複数の Retriever を使う工夫の項番誤り

### ISSUE THREAD

**Issue by tis-abe-akira** [GenerativeAgents/agent-book#23]
https://github.com/GenerativeAgents/agent-book/blob/ceaf8cfddff83436af2405cd0b1995a3fe9197cc/chapter06/notebook.ipynb#L345

誤
## 6.4. 複数の Retriever を使う工夫

正
## 6.5. 複数の Retriever を使う工夫

**Comment by os1ma** [comment]
こちら修正しました。ご指摘ありがとうございます！

https://github.com/GenerativeAgents/agent-book/blob/main/chapter06/notebook.ipynb
