### ISSUE TITLE
URLのリンク切れ

### ISSUE THREAD

**Issue by arrowkato** [GenerativeAgents/agent-book#26]
書籍の誤植というわけではないのですが、P.173の
https://docs.ragas.io/en/latest/howtos/integrations/langfuse.html
というURLのリンク先が正常なページではありません。
→恐らくどこかでRagas側のページに更新が入ってその時のバグなのだと思います。

Ragasのページでlangfuseでヒットするページが
https://docs.ragas.io/en/stable/howtos/integrations/_langfuse/
なのですが、意図しているリンクはこちらでしょうか?

**Comment by os1ma** [comment]
ご指摘ありがとうございます！

おっしゃる通り、Ragasのドキュメントの更新により、URLが変わったようです。
意図しているリンクは共有いただいたものになります。

こちらの内容について、正誤表にも追記させていただきました。

https://github.com/GenerativeAgents/agent-book/blob/main/errata.md#%E3%81%9D%E3%81%AE%E4%BB%96
