### ISSUE TITLE
細かな言葉遣い

### ISSUE THREAD

**Issue by arrowkato** [GenerativeAgents/agent-book#28]
P.373

>  目標には「来月までに」といった時間的要素が含まれる可能性があるため、具体的な時間軸を考慮したタスク分解ができるよう、現在時刻をタスク分解のプロンプトに設定しています。

とあります。
対応するコードが、下記と思っています。

https://github.com/GenerativeAgents/agent-book/blob/a3c0f6082203129adc21cb2a0487b0e6f8043a75/chapter12/single_path_plan_generation/main.py#L43

「現在時刻」というと、 "%Y-%m-%d" よりも "%Y-%m-%d %H:%M:%S" のほうをイメージしました。

コードに文章に合わせるなら、　`現在の日付` 

文章にコードを合わせるなら、　`self.current_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")` 

かなと思いました。

**Comment by mahm** [comment]
@arrowkato 
こちらご連絡ありがとうございます！
確かに `現在の日付` の方が正確だと思われたため、正誤表に追記いたします。
