### ISSUE TITLE
Bug: "Use of 'async' not allowed" errors in Colab

### ISSUE THREAD

**Issue by HBonsai** [GenerativeAgents/agent-book#31]
## 概要

本文 P 124-125, のサンプルコード, LangChainの`astream_events`を Google Colab環境で使用すると、以下のエラーが発生します。

`Use of "async" not allowed outside of async function`

## 該当のコード

https://github.com/GenerativeAgents/agent-book/blob/288f7d6528870c1311a6afa03a04dd6390a4d3aa/chapter05/notebook.ipynb#L979

https://github.com/GenerativeAgents/agent-book/blob/288f7d6528870c1311a6afa03a04dd6390a4d3aa/chapter05/notebook.ipynb#L989

## 環境

- Google Colab
- `langchain-core==0.3.0 langchain-openai==0.2.0 langchain-community==0.3.0`
- `tavily-python==0.5.0`
- Python 3.10.12

 ## 解決策

- `nest_asyncio` および `asyncio` パッケージを使用することで正常に動作いたしました。のちほどPull Requestを送ります。

**Comment by os1ma** [comment]
@HBonsai 

Issueの起票、プルリクエストの作成ありがとうございます。

私が動作確認した範囲では、asyncの箇所に「Use of "async" not allowed outside of async function」と表示されるものの、実行自体はエラーになりませんでした。

<img width="1440" alt="スクリーンショット 2024-11-04 15 43 31" src="https://github.com/user-attachments/assets/b8afe1ed-4b09-4ad6-9f77-02463f59134c">

お手数おかけしますが、実際にエラーになる様子の画面キャプチャを共有いただけますでしょうか？

書籍の記載にも影響する内容のため、修正は慎重に扱いたく、申し訳ありませんがよろしくお願いいたします。

**Comment by os1ma** [comment]
> 確かに仰るとおり、警告を無視して実行できることを私の環境でも確認いたしました。別のSyntax Errorと混同して実行できるかどうかまで確認できていなかったようです。申し訳ありません。

実行できたとのことでよかったです！

> ただColabやPythonに慣れていない人にも向けた書籍であることを考えると、not allowedという強い言葉と見慣れない警告を見て他のユーザも私のように手を止めてしまうことも考えられます。コードの変更までは行わないまでも、README等で補足を行うのが適当でしょうか……？

READMEに記載するほど大きな問題ではないと考えているので、5章のnotebookの該当箇所にコメントを入れさせていただきました。

> `# Google Colabでは次のコードの「async」の箇所に「Use of "async" not allowed outside of async function」と表示されますが、エラーなく実行できます`

https://github.com/GenerativeAgents/agent-book/blob/main/chapter05/notebook.ipynb

こちらの件のご報告ありがとうございました！

**Comment by HBonsai** [comment]
こちらこそ丁寧なご対応ありがとうございました！
引き続きよろしくお願い致しますね。

**Comment by os1ma** [comment]
こちらこそ引き続きよろしくお願いします！
