### ISSUE TITLE
P.98の文書

### ISSUE THREAD

**Issue by sou268** [GenerativeAgents/agent-book#36]
P.97

そのうち1つ目は「docs/extras/integrations/providers/aws_s3.mdx」とありますが、例で載っているドキュメントが「docs/docs/integrations/providers/aws.mdx」になっている。

**Comment by os1ma** [comment]
ご報告ありがとうございます。
ご指摘いただいた通りの誤りでしたので、正誤表に追加させていただきました。

https://github.com/GenerativeAgents/agent-book/blob/main/errata.md
