### ISSUE TITLE
「Chat Completions APIの呼び出し」でエラーが出る

### ISSUE THREAD

**Issue by hr0t15** [GenerativeAgents/agent-book#47]
**エラーの説明**

Google Colab上で、「2.5. Chat Completions API のハンズオン」の以下のコード(書籍のP.26)を実行する。

```python
from openai import OpenAI

client = OpenAI()

response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "こんにちは！私はジョンと言います！"},
    ],
)
print(response.to_json(indent=2))
```

その場合において、以下のエラーが発生した。

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-8-a4a244a13f9f>](https://localhost:8080/#) in <cell line: 3>()
      1 from openai import OpenAI
      2 
----> 3 client = OpenAI()

2 frames
[/usr/local/lib/python3.10/dist-packages/openai/_base_client.py](https://localhost:8080/#) in __init__(self, **kwargs)
    739         kwargs.setdefault("limits", DEFAULT_CONNECTION_LIMITS)
    740         kwargs.setdefault("follow_redirects", True)
--> 741         super().__init__(**kwargs)
    742 
    743 

TypeError: Client.__init__() got an unexpected keyword argument 'proxies'
```

[OpenAI Developer Forum上での議論](https://community.openai.com/t/typeerror-asyncclient-init-got-an-unexpected-keyword-argument-proxies/1040287)にもある通り、直前のpipを以下の通りに変更することで対応した。

```
!pip install openai==1.40.6 httpx==0.27.2
```

openaiを最新版にすればこのエラーは解消できるかと思いますが、バージョンを1.40.6と固定したい場合は、httpxをダウングレードするほうがよいかと思われます。

**Comment by Yu-maru1108** [comment]
```
!pip install openai==1.40.6 httpx==0.27.2

from openai import OpenAI

client = OpenAI()

response = client.chat.completions.create(
    model = "gpt-4o-mini",
    messages=[
        {"role":"system","content":"You are a helpful assistant"}, #LLMの動作に関する指示
        {"role":"user","content":"こんにちは！私はジョンといいます！"}, #対話のためのテキストを入力
    ],
)

print(response.to_json(indent=2))

```

としてやってみたのですが、解決しないです。。。
opneaiのバージョンも最新版にしてやってみましたがダメでした。
これ以外で解決に向けてしたことは他にありませんでしょうか？

**Comment by hr0t15** [comment]
実行検証はGoogle Colab 環境のみなので、そちらでの対処法となります。  
ランタイムが接続されていない状態(接続されている場合は、「ランタイムを接続解除して削除」などを事前に実行した状態)で、pip install の行を

```
!pip install openai==1.40.6   httpx==0.27.2
```

に修正し、改めて実行することで、問題なく実行できております。

`from openai import OpenAI`し、pipでダウングレードし、再度`from openai import OpenAI`を行っても、ダウングレードされたバージョンが読み込まれず、そのままエラーになる事象は私も観測しましたので、それではないかと推定します。
(なお、特にGoogle Colabにおいては、キャッシュに起因した同様のトラブルが、openaiに限らず、ライブラリよりけりで発生するそうです)

**Comment by Yu-maru1108** [comment]
コメントありがとうございます。ランタイムの接続を解除し再度実行することで解決いたしました！ありがとうございます😊

同じような人が多く出ると思うので詳細に解決方法をコメントに残しておきます
自身も本が推奨しているgoogle colabで実行しております

TypeErrorエラー発生後
↓
1.ランタイムの接続解除して削除する
↓
2. openaiとhttpxのバージョンを変更する
`!pip install openai==1.40.6   httpx==0.27.2`
↓
3. 本の通りにコードを実行する
```python
from openai import OpenAI

client = OpenAI()

response = client.chat.completions.create(
    model = "gpt-4o-mini",
    messages=[
        {"role":"system","content":"You are a helpful assistant"}, #LLMの動作に関する指示
        {"role":"user","content":"こんにちは！私はジョンといいます！"}, #対話のためのテキストを入力
    ],
)

print(response.to_json(indent=2))
```

上記の対応をすることで解決いたしました

**Comment by os1ma** [comment]
エラーと解決策のご共有ありがとうございます。

こちらのエラーについて、他の方も遭遇する可能性が高いため、このリポジトリに既知のエラーとして掲載させていただきました。

https://github.com/GenerativeAgents/agent-book?tab=readme-ov-file#%E6%97%A2%E7%9F%A5%E3%81%AE%E3%82%A8%E3%83%A9%E3%83%BC

また2章と3章のノートブックのファイルにも、同様の内容を記載しました。（4章以降ではこのエラーは発生しなくなっている認識です）

- https://github.com/GenerativeAgents/agent-book/blob/main/chapter02/notebook.ipynb
- https://github.com/GenerativeAgents/agent-book/blob/main/chapter03/notebook.ipynb

こちらのIssueはクローズさせていただきます。

ありがとうございました！
